version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123qwe
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-db:/var/lib/mysql
