version: '3.8'
services:
    database-server:
        container_name: curso-mvc-db-server
        image: mysql:8.0
        cap_add:
            - SYS_NICE
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=123qwe
        ports:
            - '3306:3306'
        volumes:
            - ./mysql-db:/var/lib/mysql
        networks:
            - spring-network    
                  #    app-server:
                  #            container_name: curso-mvc-server
                  #            build:
                  #                context: ./app/
                  #                dockerfile: Dockerfile
                  #            image: curso-mvc-server:latest
                  #            ports:
                  #                - 8080#:8080
                  #            networks:
                  #                - spring-network
networks:
    spring-network:
        driver: bridge
